// <auto-generated />
using System;
using BuffteksWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuffteksWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181129050213_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BuffteksWebApp.Models.Client", b =>
                {
                    b.Property<int>("ClientID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ClientID");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Member", b =>
                {
                    b.Property<int>("MemberID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.Property<int?>("ProjectID");

                    b.HasKey("MemberID");

                    b.HasIndex("ProjectID");

                    b.ToTable("Members");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.MemberClient", b =>
                {
                    b.Property<int>("MemberID");

                    b.Property<int>("ClientID");

                    b.HasKey("MemberID", "ClientID");

                    b.HasIndex("ClientID");

                    b.ToTable("MemberClients");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Title");

                    b.Property<int>("TotalHours");

                    b.HasKey("ProjectID");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.ProjectMember", b =>
                {
                    b.Property<int>("ProjectID");

                    b.Property<int>("MemberId");

                    b.HasKey("ProjectID", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Member", b =>
                {
                    b.HasOne("BuffteksWebApp.Models.Project")
                        .WithMany("Members")
                        .HasForeignKey("ProjectID");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.MemberClient", b =>
                {
                    b.HasOne("BuffteksWebApp.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuffteksWebApp.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("BuffteksWebApp.Models.ProjectMember", b =>
                {
                    b.HasOne("BuffteksWebApp.Models.Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuffteksWebApp.Models.Project", "Project")
                        .WithMany()
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
