// <auto-generated />
using System;
using BuffteksWebApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BuffteksWebApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20181207040253_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024");

            modelBuilder.Entity("BuffteksWebApp.Models.Person", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Email");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("PhoneNumber");

                    b.HasKey("ID");

                    b.ToTable("Person");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Person");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Project", b =>
                {
                    b.Property<int>("ProjectID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("BeginDate");

                    b.Property<DateTime>("EndDate");

                    b.Property<string>("Title");

                    b.Property<int>("TotalHours");

                    b.HasKey("ProjectID");

                    b.ToTable("Project");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.ProjectPerson", b =>
                {
                    b.Property<int>("PersonID");

                    b.Property<int>("ProjectID");

                    b.HasKey("PersonID", "ProjectID");

                    b.HasIndex("ProjectID");

                    b.ToTable("ProjectPersons");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Client", b =>
                {
                    b.HasBaseType("BuffteksWebApp.Models.Person");

                    b.Property<int>("ClientID");

                    b.ToTable("Client");

                    b.HasDiscriminator().HasValue("Client");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.Member", b =>
                {
                    b.HasBaseType("BuffteksWebApp.Models.Person");

                    b.Property<int>("MemberID");

                    b.ToTable("Member");

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("BuffteksWebApp.Models.ProjectPerson", b =>
                {
                    b.HasOne("BuffteksWebApp.Models.Person", "Person")
                        .WithMany("Projects")
                        .HasForeignKey("PersonID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BuffteksWebApp.Models.Project", "Project")
                        .WithMany("ProjectPeople")
                        .HasForeignKey("ProjectID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
